// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlateE_learning.Data;

#nullable disable

namespace PlateE_learning.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716114844_UpdateModelsAndRelations")]
    partial class UpdateModelsAndRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApprenantCours", b =>
                {
                    b.Property<int>("ApprenantsId")
                        .HasColumnType("int");

                    b.Property<int>("CoursSuivisId")
                        .HasColumnType("int");

                    b.HasKey("ApprenantsId", "CoursSuivisId");

                    b.HasIndex("CoursSuivisId");

                    b.ToTable("ApprenantCours");
                });

            modelBuilder.Entity("PlateE_learning.Models.Certificat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomApprenant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroUnique")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Signataire")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitreCours")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApprenantId");

                    b.ToTable("Certificats");
                });

            modelBuilder.Entity("PlateE_learning.Models.Chapitre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CoursId")
                        .HasColumnType("int");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.ToTable("Chapitres");
                });

            modelBuilder.Entity("PlateE_learning.Models.Cours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EnseignantId")
                        .HasColumnType("int");

                    b.Property<string>("MiniatureUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnseignantId");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("PlateE_learning.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursId")
                        .HasColumnType("int");

                    b.Property<int>("NoteMax")
                        .HasColumnType("int");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("PlateE_learning.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("UserType").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PlateE_learning.Models.Administrateur", b =>
                {
                    b.HasBaseType("PlateE_learning.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Administrateur");
                });

            modelBuilder.Entity("PlateE_learning.Models.Apprenant", b =>
                {
                    b.HasBaseType("PlateE_learning.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Apprenant");
                });

            modelBuilder.Entity("PlateE_learning.Models.Enseignant", b =>
                {
                    b.HasBaseType("PlateE_learning.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Enseignant");
                });

            modelBuilder.Entity("ApprenantCours", b =>
                {
                    b.HasOne("PlateE_learning.Models.Apprenant", null)
                        .WithMany()
                        .HasForeignKey("ApprenantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateE_learning.Models.Cours", null)
                        .WithMany()
                        .HasForeignKey("CoursSuivisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlateE_learning.Models.Certificat", b =>
                {
                    b.HasOne("PlateE_learning.Models.Apprenant", null)
                        .WithMany("Certificats")
                        .HasForeignKey("ApprenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlateE_learning.Models.Chapitre", b =>
                {
                    b.HasOne("PlateE_learning.Models.Cours", "Cours")
                        .WithMany("Chapitres")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");
                });

            modelBuilder.Entity("PlateE_learning.Models.Cours", b =>
                {
                    b.HasOne("PlateE_learning.Models.Enseignant", "Enseignant")
                        .WithMany("CoursCrees")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("PlateE_learning.Models.Evaluation", b =>
                {
                    b.HasOne("PlateE_learning.Models.Cours", "Cours")
                        .WithMany("Evaluations")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");
                });

            modelBuilder.Entity("PlateE_learning.Models.Cours", b =>
                {
                    b.Navigation("Chapitres");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("PlateE_learning.Models.Apprenant", b =>
                {
                    b.Navigation("Certificats");
                });

            modelBuilder.Entity("PlateE_learning.Models.Enseignant", b =>
                {
                    b.Navigation("CoursCrees");
                });
#pragma warning restore 612, 618
        }
    }
}
