@startuml
left to right direction

actor Enseignant as E
actor Administrateur as A
actor Apprenant as P

rectangle "Plateforme de formations certifiantes" {
  (Créer un cours) as CC
  (Ajouter chapitres) as AC
  (Ajouter évaluations) as AE
  (Générer plan du cours) as GP
  (Personnaliser certificat) as PC
  (Suivre un cours) as SC
  (Passer une évaluation) as PE
  (Recevoir certificat) as RC
  (Télécharger certificat) as TC
  (Gérer utilisateurs) as GU
  (S'inscrire à un cours) as SI
  (S'authentifier à la plateforme) as SP
  (Supprimer les cours non autorisés) as SCA
  (Supprimer les utilisateurs non autorisés) as SUA
  (Gérer son profil) as GPF
  (Consulter statistiques) as CS

  ' Relations include
  SC .> SI : <<inclut>>
  SC .> GP : <<inclut>>
  PE .> RC : <<inclut>>
  RC .> TC : <<inclut>>
  GU .> SP : <<inclut>>
  SUA .> SP : <<inclut>>
  SCA .> SP : <<inclut>>
  GPF .> SP : <<inclut>>
}

' Enseignant
E --> CC
E --> AC
E --> AE
E --> PC
E --> GP
E --> SP
E --> GPF

' Apprenant
P --> SC
P --> PE
P --> RC
P --> TC
P --> SI
P --> SP
P --> GPF

' Administrateur
A --> GU
A --> SCA
A --> SUA
A --> CS
A --> SP
A --> GPF

@enduml
